apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: flask-app
      tier: backend
  template:
    metadata:
      labels:
        app: flask-app
        tier: backend
    spec:
      containers:
      - name: flask-app-container
        image: vdnt22/my-flask-app 
        ports:
        - containerPort: 5000  
